### ISSUE TITLE
Typeset & View (PDF) no longer works on this last update

### ISSUE THREAD

**Issue by bmedinab** [textmate/latex.tmbundle#118] opened 2015-02-12 03:02 UTC
I get the next error after updating (OS X 135122 10.10.2):
*Failure running “Typeset & View (PDF)”.*
*Command returned status code 1.*

I have already followed the guide to set default values to text mate and the error hasn't improved.
This is what I get:
<pre>
Typesetting “Decidido.tex”…
Processing: Decidido.tex
Document Class: book 2014/09/29 v1.4h Standard LaTeX document class
Processing: Capitulos/encabezados.tex
Including: resources/logo.png
Traceback (most recent call last): File "/Users/userhome/Library/Application Support/TextMate/Managed/Bundles/LaTeX.tmbundle/Support/bin/texmate.py", line 1061, in status = run_latex(command, filename, cache_filename, verbose) File "/Users/userhome/Library/Application Support/TextMate/Managed/Bundles/LaTeX.tmbundle/Support/bin/texmate.py", line 224, in run_latex fatal, errors, warnings = lp.parse_stream() File "/Users/userhome/Library/Application Support/TextMate/Managed/Bundles/LaTeX.tmbundle/Support/lib/parsing.py", line 603, in parse_stream return super(LaTexParser, self).parse_stream() File "/Users/userhome/Library/Application Support/TextMate/Managed/Bundles/LaTeX.tmbundle/Support/lib/parsing.py", line 187, in parse_stream line = self.get_rewrapped_line() File "/Users/userhome/Library/Application Support/TextMate/Managed/Bundles/LaTeX.tmbundle/Support/lib/parsing.py", line 135, in get_rewrapped_line statement += line.rstrip('\n') UnicodeDecodeError: 'utf8' codec can't decode byte 0xed in position 52: invalid continuation byte
</pre>

Also the command that it suggest to be edited contains this:
<pre>
#!/usr/bin/env ruby18
# coding: utf-8

require ENV["TM_SUPPORT_PATH"] + "/lib/tm/process"
require ENV["TM_SUPPORT_PATH"] + "/lib/tm/htmloutput"
require ENV["TM_SUPPORT_PATH"] + "/lib/tm/save_current_document"

# To enable the typesetting of unsaved documents, you must change the “Save” setting of
# this command to “Current File” and add the variable TM_LATEX_AUTOSAVE to TextMate's
# Shell Variables preferences. Be warned that your document must be encoded as UTF-8 if
# you excercise this option — becauseTextMate.save_current_document cannot know the file
# encoding you prefer.

TextMate.save_current_document unless ENV["TM_LATEX_AUTOSAVE"].nil?

texmate = ENV["TM_BUNDLE_SUPPORT"] + "/bin/texmate.py"
engine_version = TextMate::Process.run(texmate, "version")
TextMate::HTMLOutput.show(:title => "Typesetting “#{ENV["TM_DISPLAYNAME"] || File.basename(ENV["TM_FILEPATH"])}”…", :sub_title => engine_version) do |io|
  TextMate::Process.run(texmate, 'latex', :interactive_input => false) do |line|
	io << line
  end
end
::Process.exit($?.exitstatus || 0) # exitstatus is nil if our process is prematurely terminated (SIGINT)
</pre>

**Comment by sanssecours** [comment] 2015-02-12 06:38
Hi Bruno,

could you please provide a minimal sample tex document, that lets me reproduce the error? By the way, this issue is a duplicate of #117. I think it would be better if we continued the conversation over there.

Kind regards,
  René

**Closed** 2015-02-12 08:31 UTC
Labels: bug, duplicate
